# version: '3'
version: "3.8"

services:
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    ports:
      - "8080:8080"   # Spark Master web UI
      - "7077:7077"   # Spark Master port
      - "4040:4040"   # Spark application UI
    environment:
      - SPARK_MODE=master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - spark-data:/opt/spark/work-dir
      - "/mnt/c/Users/Si3ma/Desktop/spark_simulation/spark_workers_Test:/home/jovyan/data"

  spark-worker-1:
    image: apache/spark:3.5.0
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=2
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - spark-data:/opt/spark/work-dir
      - "/mnt/c/Users/Si3ma/Desktop/spark_simulation/spark_workers_Test:/home/jovyan/data"
  spark-worker-2:
    image: apache/spark:3.5.0
    container_name: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=2
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - spark-data:/opt/spark/work-dir
      - "/mnt/c/Users/Si3ma/Desktop/spark_simulation/spark_workers_Test:/home/jovyan/data"

  spark-worker-3:
    image: apache/spark:3.5.0
    container_name: spark-worker-3
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=2
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - spark-data:/opt/spark/work-dir
      - "/mnt/c/Users/Si3ma/Desktop/spark_simulation/spark_workers_Test:/home/jovyan/data"

  jupyter:
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    volumes:
      - spark-data:/opt/spark/work-dir
      - "/mnt/c/Users/Si3ma/Desktop/spark_simulation/spark_workers_Test:/home/jovyan/data"
  mlflow:
    image: openeuler/mlflow:latest
  # container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow-data:/mlruns
      - mlflow-db:/mlflow
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:////mlflow/mlflow.db
      - MLFLOW_ARTIFACT_ROOT=/mlruns
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
volumes:
  spark-data:
  mlflow-data:
  mlflow-db: