[project]
name = "open_sky_pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "m_szuberla", email = "maciej.szuberla@wp.pl" }
]
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.72",
    "delta-spark>=4.1.0",
    "opensky-api",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "pyspark==4.1.2",
    "requests>=2.34.2",
    "ruff>=0.16.3",
    "shapely>=2.1.2",
]

[project.scripts]
open_sky_pipeline= "open_sky_pipeline:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
opensky-api = { git = "https://github.com/openskynetwork/opensky-api.git", subdirectory = "python" }
